name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make lib
      run: make lib
    - name: make basic
      run: make basic
    - name: install doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen
    - name: make doc
      run: make doc
